// Code generated by go-swagger; DO NOT EDIT.

package certificate_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCertificateInfoQueryCertificateHandlerFunc turns a function with the right signature into a post certificate info query certificate handler
type PostCertificateInfoQueryCertificateHandlerFunc func(PostCertificateInfoQueryCertificateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCertificateInfoQueryCertificateHandlerFunc) Handle(params PostCertificateInfoQueryCertificateParams) middleware.Responder {
	return fn(params)
}

// PostCertificateInfoQueryCertificateHandler interface for that can handle valid post certificate info query certificate params
type PostCertificateInfoQueryCertificateHandler interface {
	Handle(PostCertificateInfoQueryCertificateParams) middleware.Responder
}

// NewPostCertificateInfoQueryCertificate creates a new http.Handler for the post certificate info query certificate operation
func NewPostCertificateInfoQueryCertificate(ctx *middleware.Context, handler PostCertificateInfoQueryCertificateHandler) *PostCertificateInfoQueryCertificate {
	return &PostCertificateInfoQueryCertificate{Context: ctx, Handler: handler}
}

/*
	PostCertificateInfoQueryCertificate swagger:route POST /certificate/info/query-certificate certificate_info postCertificateInfoQueryCertificate

query one specific certificate by certificate id
*/
type PostCertificateInfoQueryCertificate struct {
	Context *middleware.Context
	Handler PostCertificateInfoQueryCertificateHandler
}

func (o *PostCertificateInfoQueryCertificate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostCertificateInfoQueryCertificateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostCertificateInfoQueryCertificateBody post certificate info query certificate body
//
// swagger:model PostCertificateInfoQueryCertificateBody
type PostCertificateInfoQueryCertificateBody struct {

	// certificate id
	// Required: true
	CertificateID *string `json:"certificate_id"`

	// organization name
	OrganizationName string `json:"organization_name,omitempty"`
}

// Validate validates this post certificate info query certificate body
func (o *PostCertificateInfoQueryCertificateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCertificateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCertificateInfoQueryCertificateBody) validateCertificateID(formats strfmt.Registry) error {

	if err := validate.Required("query_certificate"+"."+"certificate_id", "body", o.CertificateID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post certificate info query certificate body based on context it is used
func (o *PostCertificateInfoQueryCertificateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostCertificateInfoQueryCertificateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostCertificateInfoQueryCertificateBody) UnmarshalBinary(b []byte) error {
	var res PostCertificateInfoQueryCertificateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
