// Code generated by go-swagger; DO NOT EDIT.

package certificate_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cybercert-blockchain-api/models"
)

// PostCertificateInfoHistoryOKCode is the HTTP code returned for type PostCertificateInfoHistoryOK
const PostCertificateInfoHistoryOKCode int = 200

/*
PostCertificateInfoHistoryOK OK

swagger:response postCertificateInfoHistoryOK
*/
type PostCertificateInfoHistoryOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostCertificateInfoHistoryOK creates PostCertificateInfoHistoryOK with default headers values
func NewPostCertificateInfoHistoryOK() *PostCertificateInfoHistoryOK {

	return &PostCertificateInfoHistoryOK{}
}

// WithPayload adds the payload to the post certificate info history o k response
func (o *PostCertificateInfoHistoryOK) WithPayload(payload interface{}) *PostCertificateInfoHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post certificate info history o k response
func (o *PostCertificateInfoHistoryOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCertificateInfoHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostCertificateInfoHistoryUnauthorizedCode is the HTTP code returned for type PostCertificateInfoHistoryUnauthorized
const PostCertificateInfoHistoryUnauthorizedCode int = 401

/*
PostCertificateInfoHistoryUnauthorized Unauthorized

swagger:response postCertificateInfoHistoryUnauthorized
*/
type PostCertificateInfoHistoryUnauthorized struct {
}

// NewPostCertificateInfoHistoryUnauthorized creates PostCertificateInfoHistoryUnauthorized with default headers values
func NewPostCertificateInfoHistoryUnauthorized() *PostCertificateInfoHistoryUnauthorized {

	return &PostCertificateInfoHistoryUnauthorized{}
}

// WriteResponse to the client
func (o *PostCertificateInfoHistoryUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostCertificateInfoHistoryInternalServerErrorCode is the HTTP code returned for type PostCertificateInfoHistoryInternalServerError
const PostCertificateInfoHistoryInternalServerErrorCode int = 500

/*
PostCertificateInfoHistoryInternalServerError Internal Server Error

swagger:response postCertificateInfoHistoryInternalServerError
*/
type PostCertificateInfoHistoryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostCertificateInfoHistoryInternalServerError creates PostCertificateInfoHistoryInternalServerError with default headers values
func NewPostCertificateInfoHistoryInternalServerError() *PostCertificateInfoHistoryInternalServerError {

	return &PostCertificateInfoHistoryInternalServerError{}
}

// WithPayload adds the payload to the post certificate info history internal server error response
func (o *PostCertificateInfoHistoryInternalServerError) WithPayload(payload *models.APIResponse) *PostCertificateInfoHistoryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post certificate info history internal server error response
func (o *PostCertificateInfoHistoryInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCertificateInfoHistoryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
