// Code generated by go-swagger; DO NOT EDIT.

package certificate_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCertificateInfoQueryRecordsHandlerFunc turns a function with the right signature into a post certificate info query records handler
type PostCertificateInfoQueryRecordsHandlerFunc func(PostCertificateInfoQueryRecordsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCertificateInfoQueryRecordsHandlerFunc) Handle(params PostCertificateInfoQueryRecordsParams) middleware.Responder {
	return fn(params)
}

// PostCertificateInfoQueryRecordsHandler interface for that can handle valid post certificate info query records params
type PostCertificateInfoQueryRecordsHandler interface {
	Handle(PostCertificateInfoQueryRecordsParams) middleware.Responder
}

// NewPostCertificateInfoQueryRecords creates a new http.Handler for the post certificate info query records operation
func NewPostCertificateInfoQueryRecords(ctx *middleware.Context, handler PostCertificateInfoQueryRecordsHandler) *PostCertificateInfoQueryRecords {
	return &PostCertificateInfoQueryRecords{Context: ctx, Handler: handler}
}

/*
	PostCertificateInfoQueryRecords swagger:route POST /certificate/info/query-records certificate_info postCertificateInfoQueryRecords

query certificates by query string (index)
*/
type PostCertificateInfoQueryRecords struct {
	Context *middleware.Context
	Handler PostCertificateInfoQueryRecordsHandler
}

func (o *PostCertificateInfoQueryRecords) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostCertificateInfoQueryRecordsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostCertificateInfoQueryRecordsBody post certificate info query records body
//
// swagger:model PostCertificateInfoQueryRecordsBody
type PostCertificateInfoQueryRecordsBody struct {

	// organization name
	OrganizationName string `json:"organization_name,omitempty"`

	// query string
	// Required: true
	QueryString *string `json:"query_string"`
}

// Validate validates this post certificate info query records body
func (o *PostCertificateInfoQueryRecordsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateQueryString(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCertificateInfoQueryRecordsBody) validateQueryString(formats strfmt.Registry) error {

	if err := validate.Required("query_records"+"."+"query_string", "body", o.QueryString); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post certificate info query records body based on context it is used
func (o *PostCertificateInfoQueryRecordsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostCertificateInfoQueryRecordsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostCertificateInfoQueryRecordsBody) UnmarshalBinary(b []byte) error {
	var res PostCertificateInfoQueryRecordsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
