// Code generated by go-swagger; DO NOT EDIT.

package token_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteAccessTokenRevokeHandlerFunc turns a function with the right signature into a delete access token revoke handler
type DeleteAccessTokenRevokeHandlerFunc func(DeleteAccessTokenRevokeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAccessTokenRevokeHandlerFunc) Handle(params DeleteAccessTokenRevokeParams) middleware.Responder {
	return fn(params)
}

// DeleteAccessTokenRevokeHandler interface for that can handle valid delete access token revoke params
type DeleteAccessTokenRevokeHandler interface {
	Handle(DeleteAccessTokenRevokeParams) middleware.Responder
}

// NewDeleteAccessTokenRevoke creates a new http.Handler for the delete access token revoke operation
func NewDeleteAccessTokenRevoke(ctx *middleware.Context, handler DeleteAccessTokenRevokeHandler) *DeleteAccessTokenRevoke {
	return &DeleteAccessTokenRevoke{Context: ctx, Handler: handler}
}

/*
	DeleteAccessTokenRevoke swagger:route DELETE /access-token/revoke token_registry deleteAccessTokenRevoke

DeleteAccessTokenRevoke delete access token revoke API
*/
type DeleteAccessTokenRevoke struct {
	Context *middleware.Context
	Handler DeleteAccessTokenRevokeHandler
}

func (o *DeleteAccessTokenRevoke) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteAccessTokenRevokeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteAccessTokenRevokeBody delete access token revoke body
//
// swagger:model DeleteAccessTokenRevokeBody
type DeleteAccessTokenRevokeBody struct {

	// registered organization name on blockchain
	// Required: true
	OrganizationName *string `json:"organization_name"`

	// token id
	// Required: true
	TokenID *string `json:"token_id"`
}

// Validate validates this delete access token revoke body
func (o *DeleteAccessTokenRevokeBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateOrganizationName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTokenID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteAccessTokenRevokeBody) validateOrganizationName(formats strfmt.Registry) error {

	if err := validate.Required("token_record"+"."+"organization_name", "body", o.OrganizationName); err != nil {
		return err
	}

	return nil
}

func (o *DeleteAccessTokenRevokeBody) validateTokenID(formats strfmt.Registry) error {

	if err := validate.Required("token_record"+"."+"token_id", "body", o.TokenID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete access token revoke body based on context it is used
func (o *DeleteAccessTokenRevokeBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteAccessTokenRevokeBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteAccessTokenRevokeBody) UnmarshalBinary(b []byte) error {
	var res DeleteAccessTokenRevokeBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
