// Code generated by go-swagger; DO NOT EDIT.

package token_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cybercert-blockchain-api/models"
)

// DeleteAccessTokenRevokeOKCode is the HTTP code returned for type DeleteAccessTokenRevokeOK
const DeleteAccessTokenRevokeOKCode int = 200

/*
DeleteAccessTokenRevokeOK OK

swagger:response deleteAccessTokenRevokeOK
*/
type DeleteAccessTokenRevokeOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteAccessTokenRevokeOK creates DeleteAccessTokenRevokeOK with default headers values
func NewDeleteAccessTokenRevokeOK() *DeleteAccessTokenRevokeOK {

	return &DeleteAccessTokenRevokeOK{}
}

// WithPayload adds the payload to the delete access token revoke o k response
func (o *DeleteAccessTokenRevokeOK) WithPayload(payload *models.APIResponse) *DeleteAccessTokenRevokeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete access token revoke o k response
func (o *DeleteAccessTokenRevokeOK) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAccessTokenRevokeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAccessTokenRevokeUnauthorizedCode is the HTTP code returned for type DeleteAccessTokenRevokeUnauthorized
const DeleteAccessTokenRevokeUnauthorizedCode int = 401

/*
DeleteAccessTokenRevokeUnauthorized Unauthorized

swagger:response deleteAccessTokenRevokeUnauthorized
*/
type DeleteAccessTokenRevokeUnauthorized struct {
}

// NewDeleteAccessTokenRevokeUnauthorized creates DeleteAccessTokenRevokeUnauthorized with default headers values
func NewDeleteAccessTokenRevokeUnauthorized() *DeleteAccessTokenRevokeUnauthorized {

	return &DeleteAccessTokenRevokeUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteAccessTokenRevokeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteAccessTokenRevokeForbiddenCode is the HTTP code returned for type DeleteAccessTokenRevokeForbidden
const DeleteAccessTokenRevokeForbiddenCode int = 403

/*
DeleteAccessTokenRevokeForbidden Forbidden

swagger:response deleteAccessTokenRevokeForbidden
*/
type DeleteAccessTokenRevokeForbidden struct {
}

// NewDeleteAccessTokenRevokeForbidden creates DeleteAccessTokenRevokeForbidden with default headers values
func NewDeleteAccessTokenRevokeForbidden() *DeleteAccessTokenRevokeForbidden {

	return &DeleteAccessTokenRevokeForbidden{}
}

// WriteResponse to the client
func (o *DeleteAccessTokenRevokeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteAccessTokenRevokeInternalServerErrorCode is the HTTP code returned for type DeleteAccessTokenRevokeInternalServerError
const DeleteAccessTokenRevokeInternalServerErrorCode int = 500

/*
DeleteAccessTokenRevokeInternalServerError Internal Server Error

swagger:response deleteAccessTokenRevokeInternalServerError
*/
type DeleteAccessTokenRevokeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteAccessTokenRevokeInternalServerError creates DeleteAccessTokenRevokeInternalServerError with default headers values
func NewDeleteAccessTokenRevokeInternalServerError() *DeleteAccessTokenRevokeInternalServerError {

	return &DeleteAccessTokenRevokeInternalServerError{}
}

// WithPayload adds the payload to the delete access token revoke internal server error response
func (o *DeleteAccessTokenRevokeInternalServerError) WithPayload(payload *models.APIResponse) *DeleteAccessTokenRevokeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete access token revoke internal server error response
func (o *DeleteAccessTokenRevokeInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAccessTokenRevokeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
