// Code generated by go-swagger; DO NOT EDIT.

package token_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostAccessTokenQueryRecordsHandlerFunc turns a function with the right signature into a post access token query records handler
type PostAccessTokenQueryRecordsHandlerFunc func(PostAccessTokenQueryRecordsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAccessTokenQueryRecordsHandlerFunc) Handle(params PostAccessTokenQueryRecordsParams) middleware.Responder {
	return fn(params)
}

// PostAccessTokenQueryRecordsHandler interface for that can handle valid post access token query records params
type PostAccessTokenQueryRecordsHandler interface {
	Handle(PostAccessTokenQueryRecordsParams) middleware.Responder
}

// NewPostAccessTokenQueryRecords creates a new http.Handler for the post access token query records operation
func NewPostAccessTokenQueryRecords(ctx *middleware.Context, handler PostAccessTokenQueryRecordsHandler) *PostAccessTokenQueryRecords {
	return &PostAccessTokenQueryRecords{Context: ctx, Handler: handler}
}

/*
	PostAccessTokenQueryRecords swagger:route POST /access-token/query-records token_registry postAccessTokenQueryRecords

query tokens by query string (index)
*/
type PostAccessTokenQueryRecords struct {
	Context *middleware.Context
	Handler PostAccessTokenQueryRecordsHandler
}

func (o *PostAccessTokenQueryRecords) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAccessTokenQueryRecordsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostAccessTokenQueryRecordsBody post access token query records body
//
// swagger:model PostAccessTokenQueryRecordsBody
type PostAccessTokenQueryRecordsBody struct {

	// organization name
	OrganizationName string `json:"organization_name,omitempty"`

	// query string
	// Required: true
	QueryString *string `json:"query_string"`
}

// Validate validates this post access token query records body
func (o *PostAccessTokenQueryRecordsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateQueryString(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostAccessTokenQueryRecordsBody) validateQueryString(formats strfmt.Registry) error {

	if err := validate.Required("query_records"+"."+"query_string", "body", o.QueryString); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post access token query records body based on context it is used
func (o *PostAccessTokenQueryRecordsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAccessTokenQueryRecordsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAccessTokenQueryRecordsBody) UnmarshalBinary(b []byte) error {
	var res PostAccessTokenQueryRecordsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
