// Code generated by go-swagger; DO NOT EDIT.

package token_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cybercert-blockchain-api/models"
)

// PostAccessTokenHistoryOKCode is the HTTP code returned for type PostAccessTokenHistoryOK
const PostAccessTokenHistoryOKCode int = 200

/*
PostAccessTokenHistoryOK OK

swagger:response postAccessTokenHistoryOK
*/
type PostAccessTokenHistoryOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostAccessTokenHistoryOK creates PostAccessTokenHistoryOK with default headers values
func NewPostAccessTokenHistoryOK() *PostAccessTokenHistoryOK {

	return &PostAccessTokenHistoryOK{}
}

// WithPayload adds the payload to the post access token history o k response
func (o *PostAccessTokenHistoryOK) WithPayload(payload interface{}) *PostAccessTokenHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post access token history o k response
func (o *PostAccessTokenHistoryOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccessTokenHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostAccessTokenHistoryUnauthorizedCode is the HTTP code returned for type PostAccessTokenHistoryUnauthorized
const PostAccessTokenHistoryUnauthorizedCode int = 401

/*
PostAccessTokenHistoryUnauthorized Unauthorized

swagger:response postAccessTokenHistoryUnauthorized
*/
type PostAccessTokenHistoryUnauthorized struct {
}

// NewPostAccessTokenHistoryUnauthorized creates PostAccessTokenHistoryUnauthorized with default headers values
func NewPostAccessTokenHistoryUnauthorized() *PostAccessTokenHistoryUnauthorized {

	return &PostAccessTokenHistoryUnauthorized{}
}

// WriteResponse to the client
func (o *PostAccessTokenHistoryUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostAccessTokenHistoryForbiddenCode is the HTTP code returned for type PostAccessTokenHistoryForbidden
const PostAccessTokenHistoryForbiddenCode int = 403

/*
PostAccessTokenHistoryForbidden Forbidden

swagger:response postAccessTokenHistoryForbidden
*/
type PostAccessTokenHistoryForbidden struct {
}

// NewPostAccessTokenHistoryForbidden creates PostAccessTokenHistoryForbidden with default headers values
func NewPostAccessTokenHistoryForbidden() *PostAccessTokenHistoryForbidden {

	return &PostAccessTokenHistoryForbidden{}
}

// WriteResponse to the client
func (o *PostAccessTokenHistoryForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PostAccessTokenHistoryInternalServerErrorCode is the HTTP code returned for type PostAccessTokenHistoryInternalServerError
const PostAccessTokenHistoryInternalServerErrorCode int = 500

/*
PostAccessTokenHistoryInternalServerError Internal Server Error

swagger:response postAccessTokenHistoryInternalServerError
*/
type PostAccessTokenHistoryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostAccessTokenHistoryInternalServerError creates PostAccessTokenHistoryInternalServerError with default headers values
func NewPostAccessTokenHistoryInternalServerError() *PostAccessTokenHistoryInternalServerError {

	return &PostAccessTokenHistoryInternalServerError{}
}

// WithPayload adds the payload to the post access token history internal server error response
func (o *PostAccessTokenHistoryInternalServerError) WithPayload(payload *models.APIResponse) *PostAccessTokenHistoryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post access token history internal server error response
func (o *PostAccessTokenHistoryInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccessTokenHistoryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
