// Code generated by go-swagger; DO NOT EDIT.

package token_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostAccessTokenConsumeHandlerFunc turns a function with the right signature into a post access token consume handler
type PostAccessTokenConsumeHandlerFunc func(PostAccessTokenConsumeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAccessTokenConsumeHandlerFunc) Handle(params PostAccessTokenConsumeParams) middleware.Responder {
	return fn(params)
}

// PostAccessTokenConsumeHandler interface for that can handle valid post access token consume params
type PostAccessTokenConsumeHandler interface {
	Handle(PostAccessTokenConsumeParams) middleware.Responder
}

// NewPostAccessTokenConsume creates a new http.Handler for the post access token consume operation
func NewPostAccessTokenConsume(ctx *middleware.Context, handler PostAccessTokenConsumeHandler) *PostAccessTokenConsume {
	return &PostAccessTokenConsume{Context: ctx, Handler: handler}
}

/*
	PostAccessTokenConsume swagger:route POST /access-token/consume token_registry postAccessTokenConsume

PostAccessTokenConsume post access token consume API
*/
type PostAccessTokenConsume struct {
	Context *middleware.Context
	Handler PostAccessTokenConsumeHandler
}

func (o *PostAccessTokenConsume) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAccessTokenConsumeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostAccessTokenConsumeBody post access token consume body
//
// swagger:model PostAccessTokenConsumeBody
type PostAccessTokenConsumeBody struct {

	// registered organization name on blockchain
	OrganizationName string `json:"organization_name,omitempty"`

	// token id
	// Required: true
	TokenID *string `json:"token_id"`
}

// Validate validates this post access token consume body
func (o *PostAccessTokenConsumeBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTokenID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostAccessTokenConsumeBody) validateTokenID(formats strfmt.Registry) error {

	if err := validate.Required("token_record"+"."+"token_id", "body", o.TokenID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post access token consume body based on context it is used
func (o *PostAccessTokenConsumeBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAccessTokenConsumeBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAccessTokenConsumeBody) UnmarshalBinary(b []byte) error {
	var res PostAccessTokenConsumeBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
