// Code generated by go-swagger; DO NOT EDIT.

package token_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cybercert-blockchain-api/models"
)

// PostAccessTokenStatusOKCode is the HTTP code returned for type PostAccessTokenStatusOK
const PostAccessTokenStatusOKCode int = 200

/*
PostAccessTokenStatusOK OK

swagger:response postAccessTokenStatusOK
*/
type PostAccessTokenStatusOK struct {

	/*
	  In: Body
	*/
	Payload *PostAccessTokenStatusOKBody `json:"body,omitempty"`
}

// NewPostAccessTokenStatusOK creates PostAccessTokenStatusOK with default headers values
func NewPostAccessTokenStatusOK() *PostAccessTokenStatusOK {

	return &PostAccessTokenStatusOK{}
}

// WithPayload adds the payload to the post access token status o k response
func (o *PostAccessTokenStatusOK) WithPayload(payload *PostAccessTokenStatusOKBody) *PostAccessTokenStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post access token status o k response
func (o *PostAccessTokenStatusOK) SetPayload(payload *PostAccessTokenStatusOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccessTokenStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAccessTokenStatusUnauthorizedCode is the HTTP code returned for type PostAccessTokenStatusUnauthorized
const PostAccessTokenStatusUnauthorizedCode int = 401

/*
PostAccessTokenStatusUnauthorized Unauthorized

swagger:response postAccessTokenStatusUnauthorized
*/
type PostAccessTokenStatusUnauthorized struct {
}

// NewPostAccessTokenStatusUnauthorized creates PostAccessTokenStatusUnauthorized with default headers values
func NewPostAccessTokenStatusUnauthorized() *PostAccessTokenStatusUnauthorized {

	return &PostAccessTokenStatusUnauthorized{}
}

// WriteResponse to the client
func (o *PostAccessTokenStatusUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostAccessTokenStatusForbiddenCode is the HTTP code returned for type PostAccessTokenStatusForbidden
const PostAccessTokenStatusForbiddenCode int = 403

/*
PostAccessTokenStatusForbidden Forbidden

swagger:response postAccessTokenStatusForbidden
*/
type PostAccessTokenStatusForbidden struct {
}

// NewPostAccessTokenStatusForbidden creates PostAccessTokenStatusForbidden with default headers values
func NewPostAccessTokenStatusForbidden() *PostAccessTokenStatusForbidden {

	return &PostAccessTokenStatusForbidden{}
}

// WriteResponse to the client
func (o *PostAccessTokenStatusForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PostAccessTokenStatusInternalServerErrorCode is the HTTP code returned for type PostAccessTokenStatusInternalServerError
const PostAccessTokenStatusInternalServerErrorCode int = 500

/*
PostAccessTokenStatusInternalServerError Internal Server Error

swagger:response postAccessTokenStatusInternalServerError
*/
type PostAccessTokenStatusInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostAccessTokenStatusInternalServerError creates PostAccessTokenStatusInternalServerError with default headers values
func NewPostAccessTokenStatusInternalServerError() *PostAccessTokenStatusInternalServerError {

	return &PostAccessTokenStatusInternalServerError{}
}

// WithPayload adds the payload to the post access token status internal server error response
func (o *PostAccessTokenStatusInternalServerError) WithPayload(payload *models.APIResponse) *PostAccessTokenStatusInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post access token status internal server error response
func (o *PostAccessTokenStatusInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccessTokenStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
