// Code generated by go-swagger; DO NOT EDIT.

package token_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cybercert-blockchain-api/models"
)

// PostAccessTokenConsumeOKCode is the HTTP code returned for type PostAccessTokenConsumeOK
const PostAccessTokenConsumeOKCode int = 200

/*
PostAccessTokenConsumeOK OK

swagger:response postAccessTokenConsumeOK
*/
type PostAccessTokenConsumeOK struct {

	/*
	  In: Body
	*/
	Payload *models.CreatedResponse `json:"body,omitempty"`
}

// NewPostAccessTokenConsumeOK creates PostAccessTokenConsumeOK with default headers values
func NewPostAccessTokenConsumeOK() *PostAccessTokenConsumeOK {

	return &PostAccessTokenConsumeOK{}
}

// WithPayload adds the payload to the post access token consume o k response
func (o *PostAccessTokenConsumeOK) WithPayload(payload *models.CreatedResponse) *PostAccessTokenConsumeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post access token consume o k response
func (o *PostAccessTokenConsumeOK) SetPayload(payload *models.CreatedResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccessTokenConsumeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAccessTokenConsumeUnauthorizedCode is the HTTP code returned for type PostAccessTokenConsumeUnauthorized
const PostAccessTokenConsumeUnauthorizedCode int = 401

/*
PostAccessTokenConsumeUnauthorized Unauthorized

swagger:response postAccessTokenConsumeUnauthorized
*/
type PostAccessTokenConsumeUnauthorized struct {
}

// NewPostAccessTokenConsumeUnauthorized creates PostAccessTokenConsumeUnauthorized with default headers values
func NewPostAccessTokenConsumeUnauthorized() *PostAccessTokenConsumeUnauthorized {

	return &PostAccessTokenConsumeUnauthorized{}
}

// WriteResponse to the client
func (o *PostAccessTokenConsumeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostAccessTokenConsumeForbiddenCode is the HTTP code returned for type PostAccessTokenConsumeForbidden
const PostAccessTokenConsumeForbiddenCode int = 403

/*
PostAccessTokenConsumeForbidden Forbidden

swagger:response postAccessTokenConsumeForbidden
*/
type PostAccessTokenConsumeForbidden struct {
}

// NewPostAccessTokenConsumeForbidden creates PostAccessTokenConsumeForbidden with default headers values
func NewPostAccessTokenConsumeForbidden() *PostAccessTokenConsumeForbidden {

	return &PostAccessTokenConsumeForbidden{}
}

// WriteResponse to the client
func (o *PostAccessTokenConsumeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PostAccessTokenConsumeInternalServerErrorCode is the HTTP code returned for type PostAccessTokenConsumeInternalServerError
const PostAccessTokenConsumeInternalServerErrorCode int = 500

/*
PostAccessTokenConsumeInternalServerError Internal Server Error

swagger:response postAccessTokenConsumeInternalServerError
*/
type PostAccessTokenConsumeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostAccessTokenConsumeInternalServerError creates PostAccessTokenConsumeInternalServerError with default headers values
func NewPostAccessTokenConsumeInternalServerError() *PostAccessTokenConsumeInternalServerError {

	return &PostAccessTokenConsumeInternalServerError{}
}

// WithPayload adds the payload to the post access token consume internal server error response
func (o *PostAccessTokenConsumeInternalServerError) WithPayload(payload *models.APIResponse) *PostAccessTokenConsumeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post access token consume internal server error response
func (o *PostAccessTokenConsumeInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccessTokenConsumeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
