// Code generated by go-swagger; DO NOT EDIT.

package token_registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostAccessTokenStatusHandlerFunc turns a function with the right signature into a post access token status handler
type PostAccessTokenStatusHandlerFunc func(PostAccessTokenStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAccessTokenStatusHandlerFunc) Handle(params PostAccessTokenStatusParams) middleware.Responder {
	return fn(params)
}

// PostAccessTokenStatusHandler interface for that can handle valid post access token status params
type PostAccessTokenStatusHandler interface {
	Handle(PostAccessTokenStatusParams) middleware.Responder
}

// NewPostAccessTokenStatus creates a new http.Handler for the post access token status operation
func NewPostAccessTokenStatus(ctx *middleware.Context, handler PostAccessTokenStatusHandler) *PostAccessTokenStatus {
	return &PostAccessTokenStatus{Context: ctx, Handler: handler}
}

/*
	PostAccessTokenStatus swagger:route POST /access-token/status token_registry postAccessTokenStatus

PostAccessTokenStatus post access token status API
*/
type PostAccessTokenStatus struct {
	Context *middleware.Context
	Handler PostAccessTokenStatusHandler
}

func (o *PostAccessTokenStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAccessTokenStatusParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostAccessTokenStatusBody post access token status body
//
// swagger:model PostAccessTokenStatusBody
type PostAccessTokenStatusBody struct {

	// registered organization name on blockchain
	OrganizationName string `json:"organization_name,omitempty"`

	// token id
	// Required: true
	TokenID *string `json:"token_id"`
}

// Validate validates this post access token status body
func (o *PostAccessTokenStatusBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTokenID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostAccessTokenStatusBody) validateTokenID(formats strfmt.Registry) error {

	if err := validate.Required("token_record"+"."+"token_id", "body", o.TokenID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post access token status body based on context it is used
func (o *PostAccessTokenStatusBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAccessTokenStatusBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAccessTokenStatusBody) UnmarshalBinary(b []byte) error {
	var res PostAccessTokenStatusBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostAccessTokenStatusOKBody post access token status o k body
//
// swagger:model PostAccessTokenStatusOKBody
type PostAccessTokenStatusOKBody struct {

	// status
	Status string `json:"status,omitempty"`

	// token id
	TokenID string `json:"token_id,omitempty"`
}

// Validate validates this post access token status o k body
func (o *PostAccessTokenStatusOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post access token status o k body based on context it is used
func (o *PostAccessTokenStatusOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAccessTokenStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAccessTokenStatusOKBody) UnmarshalBinary(b []byte) error {
	var res PostAccessTokenStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
