// Code generated by go-swagger; DO NOT EDIT.

// Package restapi eCertification Blockchain API
//
//	eCert Blockchain API endpoint for query and invoke chaincode in Hyperledger Fabric.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
