// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "eCert Blockchain API endpoint for query and invoke chaincode in Hyperledger Fabric.",
    "title": "eCertification Blockchain API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/access-token/change-token-owner": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "token_id",
                "owner"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "owner": {
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/consume": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "token_id"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/history": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/issue/root": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "args": {
                  "$ref": "#/definitions/IssueRootTokenPayload"
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/issue/standard": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "args": {
                  "$ref": "#/definitions/IssueStandardTokenPayload"
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/issue/transferable": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "args": {
                  "$ref": "#/definitions/IssueTransferableTokenPayload"
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/query": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "query_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "token_id"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/query-records": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "summary": "query tokens by query string (index)",
        "parameters": [
          {
            "name": "query_records",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "query_string"
              ],
              "properties": {
                "organization_name": {
                  "type": "string"
                },
                "query_string": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/revoke": {
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "organization_name",
                "token_id"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/status": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "token_id"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/history": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "parameters": [
          {
            "name": "get_history",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "certificate_id"
              ],
              "properties": {
                "certificate_id": {
                  "type": "string"
                },
                "organization_name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/issue": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "parameters": [
          {
            "name": "certificate_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "certificate_details": {
                  "$ref": "#/definitions/CertificateInfo"
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/issue-batch": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "parameters": [
          {
            "name": "certificate_batch",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "callback_url": {
                  "description": "callback endpoint to notify platform for each issued certificate",
                  "type": "string"
                },
                "certificate_details": {
                  "description": "certificate details csv content",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/CertificateInfo"
                  }
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "template": {
                  "$ref": "#/definitions/CertificateTemplate"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/query-certificate": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "summary": "query one specific certificate by certificate id",
        "parameters": [
          {
            "name": "query_certificate",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "certificate_id"
              ],
              "properties": {
                "certificate_id": {
                  "type": "string"
                },
                "organization_name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/query-records": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "summary": "query certificates by query string (index)",
        "parameters": [
          {
            "name": "query_records",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "query_string"
              ],
              "properties": {
                "organization_name": {
                  "type": "string"
                },
                "query_string": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/revoke": {
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "parameters": [
          {
            "name": "revoke_certificate",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "certificate_id"
              ],
              "properties": {
                "certificate_id": {
                  "type": "string"
                },
                "organization_name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/template/": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_template"
        ],
        "summary": "upsert certificate template on blockhain",
        "parameters": [
          {
            "name": "certificate_template",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "template": {
                  "$ref": "#/definitions/CertificateTemplate"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/template/history": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_template"
        ],
        "summary": "query certificate template modification history",
        "parameters": [
          {
            "name": "get_history",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "template_key"
              ],
              "properties": {
                "organization_name": {
                  "type": "string"
                },
                "template_key": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/template/query": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_template"
        ],
        "summary": "query certificate template by key",
        "parameters": [
          {
            "name": "query_template",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "template_key"
              ],
              "properties": {
                "organization_name": {
                  "type": "string"
                },
                "template_key": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/healthcheck/ready": {
      "get": {
        "tags": [
          "healthcheck"
        ],
        "summary": "Returns status of service availability",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "version": {
                  "type": "string"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "CertificateInfo": {
      "type": "object",
      "properties": {
        "certificate_holder": {
          "type": "string"
        },
        "certificate_id": {
          "type": "string"
        },
        "certificate_signature": {
          "type": "string"
        },
        "course_name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "extras": {
          "type": "object"
        },
        "issued_at": {
          "type": "string"
        },
        "issuer_name": {
          "type": "string"
        },
        "module_name": {
          "type": "string"
        },
        "template_ref": {
          "type": "string"
        }
      }
    },
    "CertificateTemplate": {
      "type": "object",
      "properties": {
        "issuer_id": {
          "type": "string"
        },
        "issuer_name": {
          "type": "string"
        },
        "source_type": {
          "type": "string"
        },
        "template_key": {
          "type": "string"
        },
        "template_source": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "CreatedResponse": {
      "type": "object",
      "properties": {
        "transaction_id": {
          "type": "string"
        }
      }
    },
    "IssueRootTokenPayload": {
      "type": "object",
      "properties": {
        "certificate_id": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        },
        "token_id": {
          "type": "string"
        }
      }
    },
    "IssueStandardTokenPayload": {
      "type": "object",
      "properties": {
        "access_quota": {
          "type": "integer"
        },
        "amount": {
          "type": "integer"
        },
        "expiry_date": {
          "description": "unix timestamp in second (UTC)",
          "type": "integer"
        },
        "issuer_token_id": {
          "type": "string"
        },
        "recipient": {
          "type": "string"
        },
        "token_id": {
          "type": "string"
        }
      }
    },
    "IssueTransferableTokenPayload": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "integer"
        },
        "expiry_date": {
          "description": "unix timestamp in second (UTC)",
          "type": "integer"
        },
        "issuer_token_id": {
          "type": "string"
        },
        "monthly_token_quota": {
          "type": "integer"
        },
        "recipient": {
          "type": "string"
        },
        "token_id": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "API wrapper for certificate info chaincode",
      "name": "certificate_info"
    },
    {
      "description": "API wrapper for certificate template chaincode",
      "name": "certificate_template"
    },
    {
      "description": "Healthcheck for readiness and liveness",
      "name": "healthcheck"
    },
    {
      "description": "API wrapper for token registry chaincode",
      "name": "token_registry"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "eCert Blockchain API endpoint for query and invoke chaincode in Hyperledger Fabric.",
    "title": "eCertification Blockchain API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/access-token/change-token-owner": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "token_id",
                "owner"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "owner": {
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/consume": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "token_id"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/history": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/issue/root": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "args": {
                  "$ref": "#/definitions/IssueRootTokenPayload"
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/issue/standard": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "args": {
                  "$ref": "#/definitions/IssueStandardTokenPayload"
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/issue/transferable": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "args": {
                  "$ref": "#/definitions/IssueTransferableTokenPayload"
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/query": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "query_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "token_id"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/query-records": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "summary": "query tokens by query string (index)",
        "parameters": [
          {
            "name": "query_records",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "query_string"
              ],
              "properties": {
                "organization_name": {
                  "type": "string"
                },
                "query_string": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/revoke": {
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "organization_name",
                "token_id"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/access-token/status": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "token_registry"
        ],
        "parameters": [
          {
            "name": "token_record",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "token_id"
              ],
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                },
                "token_id": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/history": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "parameters": [
          {
            "name": "get_history",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "certificate_id"
              ],
              "properties": {
                "certificate_id": {
                  "type": "string"
                },
                "organization_name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/issue": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "parameters": [
          {
            "name": "certificate_record",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "certificate_details": {
                  "$ref": "#/definitions/CertificateInfo"
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/issue-batch": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "parameters": [
          {
            "name": "certificate_batch",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "callback_url": {
                  "description": "callback endpoint to notify platform for each issued certificate",
                  "type": "string"
                },
                "certificate_details": {
                  "description": "certificate details csv content",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/CertificateInfo"
                  }
                },
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "template": {
                  "$ref": "#/definitions/CertificateTemplate"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/query-certificate": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "summary": "query one specific certificate by certificate id",
        "parameters": [
          {
            "name": "query_certificate",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "certificate_id"
              ],
              "properties": {
                "certificate_id": {
                  "type": "string"
                },
                "organization_name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/query-records": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "summary": "query certificates by query string (index)",
        "parameters": [
          {
            "name": "query_records",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "query_string"
              ],
              "properties": {
                "organization_name": {
                  "type": "string"
                },
                "query_string": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/info/revoke": {
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_info"
        ],
        "parameters": [
          {
            "name": "revoke_certificate",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "certificate_id"
              ],
              "properties": {
                "certificate_id": {
                  "type": "string"
                },
                "organization_name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/template/": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_template"
        ],
        "summary": "upsert certificate template on blockhain",
        "parameters": [
          {
            "name": "certificate_template",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "organization_name": {
                  "description": "registered organization name on blockchain",
                  "type": "string"
                },
                "template": {
                  "$ref": "#/definitions/CertificateTemplate"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CreatedResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/template/history": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_template"
        ],
        "summary": "query certificate template modification history",
        "parameters": [
          {
            "name": "get_history",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "template_key"
              ],
              "properties": {
                "organization_name": {
                  "type": "string"
                },
                "template_key": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/certificate/template/query": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "certificate_template"
        ],
        "summary": "query certificate template by key",
        "parameters": [
          {
            "name": "query_template",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "template_key"
              ],
              "properties": {
                "organization_name": {
                  "type": "string"
                },
                "template_key": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/healthcheck/ready": {
      "get": {
        "tags": [
          "healthcheck"
        ],
        "summary": "Returns status of service availability",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "version": {
                  "type": "string"
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "CertificateInfo": {
      "type": "object",
      "properties": {
        "certificate_holder": {
          "type": "string"
        },
        "certificate_id": {
          "type": "string"
        },
        "certificate_signature": {
          "type": "string"
        },
        "course_name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "extras": {
          "type": "object"
        },
        "issued_at": {
          "type": "string"
        },
        "issuer_name": {
          "type": "string"
        },
        "module_name": {
          "type": "string"
        },
        "template_ref": {
          "type": "string"
        }
      }
    },
    "CertificateTemplate": {
      "type": "object",
      "properties": {
        "issuer_id": {
          "type": "string"
        },
        "issuer_name": {
          "type": "string"
        },
        "source_type": {
          "type": "string"
        },
        "template_key": {
          "type": "string"
        },
        "template_source": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "CreatedResponse": {
      "type": "object",
      "properties": {
        "transaction_id": {
          "type": "string"
        }
      }
    },
    "IssueRootTokenPayload": {
      "type": "object",
      "properties": {
        "certificate_id": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        },
        "token_id": {
          "type": "string"
        }
      }
    },
    "IssueStandardTokenPayload": {
      "type": "object",
      "properties": {
        "access_quota": {
          "type": "integer"
        },
        "amount": {
          "type": "integer"
        },
        "expiry_date": {
          "description": "unix timestamp in second (UTC)",
          "type": "integer"
        },
        "issuer_token_id": {
          "type": "string"
        },
        "recipient": {
          "type": "string"
        },
        "token_id": {
          "type": "string"
        }
      }
    },
    "IssueTransferableTokenPayload": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "integer"
        },
        "expiry_date": {
          "description": "unix timestamp in second (UTC)",
          "type": "integer"
        },
        "issuer_token_id": {
          "type": "string"
        },
        "monthly_token_quota": {
          "type": "integer"
        },
        "recipient": {
          "type": "string"
        },
        "token_id": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "API wrapper for certificate info chaincode",
      "name": "certificate_info"
    },
    {
      "description": "API wrapper for certificate template chaincode",
      "name": "certificate_template"
    },
    {
      "description": "Healthcheck for readiness and liveness",
      "name": "healthcheck"
    },
    {
      "description": "API wrapper for token registry chaincode",
      "name": "token_registry"
    }
  ]
}`))
}
