// Code generated by go-swagger; DO NOT EDIT.

package certificate_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"
)

// NewPostCertificateTemplateQueryParams creates a new PostCertificateTemplateQueryParams object
//
// There are no default values defined in the spec.
func NewPostCertificateTemplateQueryParams() PostCertificateTemplateQueryParams {

	return PostCertificateTemplateQueryParams{}
}

// PostCertificateTemplateQueryParams contains all the bound params for the post certificate template query operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostCertificateTemplateQuery
type PostCertificateTemplateQueryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	QueryTemplate PostCertificateTemplateQueryBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostCertificateTemplateQueryParams() beforehand.
func (o *PostCertificateTemplateQueryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostCertificateTemplateQueryBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("queryTemplate", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.QueryTemplate = body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
