// Code generated by go-swagger; DO NOT EDIT.

package certificate_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCertificateTemplateHistoryHandlerFunc turns a function with the right signature into a post certificate template history handler
type PostCertificateTemplateHistoryHandlerFunc func(PostCertificateTemplateHistoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCertificateTemplateHistoryHandlerFunc) Handle(params PostCertificateTemplateHistoryParams) middleware.Responder {
	return fn(params)
}

// PostCertificateTemplateHistoryHandler interface for that can handle valid post certificate template history params
type PostCertificateTemplateHistoryHandler interface {
	Handle(PostCertificateTemplateHistoryParams) middleware.Responder
}

// NewPostCertificateTemplateHistory creates a new http.Handler for the post certificate template history operation
func NewPostCertificateTemplateHistory(ctx *middleware.Context, handler PostCertificateTemplateHistoryHandler) *PostCertificateTemplateHistory {
	return &PostCertificateTemplateHistory{Context: ctx, Handler: handler}
}

/*
	PostCertificateTemplateHistory swagger:route POST /certificate/template/history certificate_template postCertificateTemplateHistory

query certificate template modification history
*/
type PostCertificateTemplateHistory struct {
	Context *middleware.Context
	Handler PostCertificateTemplateHistoryHandler
}

func (o *PostCertificateTemplateHistory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostCertificateTemplateHistoryParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostCertificateTemplateHistoryBody post certificate template history body
//
// swagger:model PostCertificateTemplateHistoryBody
type PostCertificateTemplateHistoryBody struct {

	// organization name
	OrganizationName string `json:"organization_name,omitempty"`

	// template key
	// Required: true
	TemplateKey *string `json:"template_key"`
}

// Validate validates this post certificate template history body
func (o *PostCertificateTemplateHistoryBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTemplateKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCertificateTemplateHistoryBody) validateTemplateKey(formats strfmt.Registry) error {

	if err := validate.Required("get_history"+"."+"template_key", "body", o.TemplateKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post certificate template history body based on context it is used
func (o *PostCertificateTemplateHistoryBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostCertificateTemplateHistoryBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostCertificateTemplateHistoryBody) UnmarshalBinary(b []byte) error {
	var res PostCertificateTemplateHistoryBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
