// Code generated by go-swagger; DO NOT EDIT.

package certificate_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"cybercert-blockchain-api/models"
)

// PostCertificateTemplateHandlerFunc turns a function with the right signature into a post certificate template handler
type PostCertificateTemplateHandlerFunc func(PostCertificateTemplateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCertificateTemplateHandlerFunc) Handle(params PostCertificateTemplateParams) middleware.Responder {
	return fn(params)
}

// PostCertificateTemplateHandler interface for that can handle valid post certificate template params
type PostCertificateTemplateHandler interface {
	Handle(PostCertificateTemplateParams) middleware.Responder
}

// NewPostCertificateTemplate creates a new http.Handler for the post certificate template operation
func NewPostCertificateTemplate(ctx *middleware.Context, handler PostCertificateTemplateHandler) *PostCertificateTemplate {
	return &PostCertificateTemplate{Context: ctx, Handler: handler}
}

/*
	PostCertificateTemplate swagger:route POST /certificate/template/ certificate_template postCertificateTemplate

upsert certificate template on blockhain
*/
type PostCertificateTemplate struct {
	Context *middleware.Context
	Handler PostCertificateTemplateHandler
}

func (o *PostCertificateTemplate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostCertificateTemplateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostCertificateTemplateBody post certificate template body
//
// swagger:model PostCertificateTemplateBody
type PostCertificateTemplateBody struct {

	// registered organization name on blockchain
	OrganizationName string `json:"organization_name,omitempty"`

	// template
	Template *models.CertificateTemplate `json:"template,omitempty"`
}

// Validate validates this post certificate template body
func (o *PostCertificateTemplateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTemplate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCertificateTemplateBody) validateTemplate(formats strfmt.Registry) error {
	if swag.IsZero(o.Template) { // not required
		return nil
	}

	if o.Template != nil {
		if err := o.Template.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("certificate_template" + "." + "template")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("certificate_template" + "." + "template")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post certificate template body based on the context it is used
func (o *PostCertificateTemplateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateTemplate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCertificateTemplateBody) contextValidateTemplate(ctx context.Context, formats strfmt.Registry) error {

	if o.Template != nil {
		if err := o.Template.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("certificate_template" + "." + "template")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("certificate_template" + "." + "template")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostCertificateTemplateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostCertificateTemplateBody) UnmarshalBinary(b []byte) error {
	var res PostCertificateTemplateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
