// Code generated by go-swagger; DO NOT EDIT.

package certificate_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cybercert-blockchain-api/models"
)

// PostCertificateTemplateCreatedCode is the HTTP code returned for type PostCertificateTemplateCreated
const PostCertificateTemplateCreatedCode int = 201

/*
PostCertificateTemplateCreated OK

swagger:response postCertificateTemplateCreated
*/
type PostCertificateTemplateCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CreatedResponse `json:"body,omitempty"`
}

// NewPostCertificateTemplateCreated creates PostCertificateTemplateCreated with default headers values
func NewPostCertificateTemplateCreated() *PostCertificateTemplateCreated {

	return &PostCertificateTemplateCreated{}
}

// WithPayload adds the payload to the post certificate template created response
func (o *PostCertificateTemplateCreated) WithPayload(payload *models.CreatedResponse) *PostCertificateTemplateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post certificate template created response
func (o *PostCertificateTemplateCreated) SetPayload(payload *models.CreatedResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCertificateTemplateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostCertificateTemplateUnauthorizedCode is the HTTP code returned for type PostCertificateTemplateUnauthorized
const PostCertificateTemplateUnauthorizedCode int = 401

/*
PostCertificateTemplateUnauthorized Unauthorized

swagger:response postCertificateTemplateUnauthorized
*/
type PostCertificateTemplateUnauthorized struct {
}

// NewPostCertificateTemplateUnauthorized creates PostCertificateTemplateUnauthorized with default headers values
func NewPostCertificateTemplateUnauthorized() *PostCertificateTemplateUnauthorized {

	return &PostCertificateTemplateUnauthorized{}
}

// WriteResponse to the client
func (o *PostCertificateTemplateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostCertificateTemplateInternalServerErrorCode is the HTTP code returned for type PostCertificateTemplateInternalServerError
const PostCertificateTemplateInternalServerErrorCode int = 500

/*
PostCertificateTemplateInternalServerError Internal Server Error

swagger:response postCertificateTemplateInternalServerError
*/
type PostCertificateTemplateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostCertificateTemplateInternalServerError creates PostCertificateTemplateInternalServerError with default headers values
func NewPostCertificateTemplateInternalServerError() *PostCertificateTemplateInternalServerError {

	return &PostCertificateTemplateInternalServerError{}
}

// WithPayload adds the payload to the post certificate template internal server error response
func (o *PostCertificateTemplateInternalServerError) WithPayload(payload *models.APIResponse) *PostCertificateTemplateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post certificate template internal server error response
func (o *PostCertificateTemplateInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCertificateTemplateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
