// Code generated by go-swagger; DO NOT EDIT.

package healthcheck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetHealthcheckReadyHandlerFunc turns a function with the right signature into a get healthcheck ready handler
type GetHealthcheckReadyHandlerFunc func(GetHealthcheckReadyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHealthcheckReadyHandlerFunc) Handle(params GetHealthcheckReadyParams) middleware.Responder {
	return fn(params)
}

// GetHealthcheckReadyHandler interface for that can handle valid get healthcheck ready params
type GetHealthcheckReadyHandler interface {
	Handle(GetHealthcheckReadyParams) middleware.Responder
}

// NewGetHealthcheckReady creates a new http.Handler for the get healthcheck ready operation
func NewGetHealthcheckReady(ctx *middleware.Context, handler GetHealthcheckReadyHandler) *GetHealthcheckReady {
	return &GetHealthcheckReady{Context: ctx, Handler: handler}
}

/*
	GetHealthcheckReady swagger:route GET /healthcheck/ready healthcheck getHealthcheckReady

Returns status of service availability
*/
type GetHealthcheckReady struct {
	Context *middleware.Context
	Handler GetHealthcheckReadyHandler
}

func (o *GetHealthcheckReady) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetHealthcheckReadyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetHealthcheckReadyOKBody get healthcheck ready o k body
//
// swagger:model GetHealthcheckReadyOKBody
type GetHealthcheckReadyOKBody struct {

	// message
	Message string `json:"message,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this get healthcheck ready o k body
func (o *GetHealthcheckReadyOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get healthcheck ready o k body based on context it is used
func (o *GetHealthcheckReadyOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetHealthcheckReadyOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHealthcheckReadyOKBody) UnmarshalBinary(b []byte) error {
	var res GetHealthcheckReadyOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
