// Code generated by go-swagger; DO NOT EDIT.

package healthcheck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cybercert-blockchain-api/models"
)

// GetHealthcheckReadyOKCode is the HTTP code returned for type GetHealthcheckReadyOK
const GetHealthcheckReadyOKCode int = 200

/*
GetHealthcheckReadyOK OK

swagger:response getHealthcheckReadyOK
*/
type GetHealthcheckReadyOK struct {

	/*
	  In: Body
	*/
	Payload *GetHealthcheckReadyOKBody `json:"body,omitempty"`
}

// NewGetHealthcheckReadyOK creates GetHealthcheckReadyOK with default headers values
func NewGetHealthcheckReadyOK() *GetHealthcheckReadyOK {

	return &GetHealthcheckReadyOK{}
}

// WithPayload adds the payload to the get healthcheck ready o k response
func (o *GetHealthcheckReadyOK) WithPayload(payload *GetHealthcheckReadyOKBody) *GetHealthcheckReadyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get healthcheck ready o k response
func (o *GetHealthcheckReadyOK) SetPayload(payload *GetHealthcheckReadyOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthcheckReadyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHealthcheckReadyServiceUnavailableCode is the HTTP code returned for type GetHealthcheckReadyServiceUnavailable
const GetHealthcheckReadyServiceUnavailableCode int = 503

/*
GetHealthcheckReadyServiceUnavailable Service Unavailable

swagger:response getHealthcheckReadyServiceUnavailable
*/
type GetHealthcheckReadyServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetHealthcheckReadyServiceUnavailable creates GetHealthcheckReadyServiceUnavailable with default headers values
func NewGetHealthcheckReadyServiceUnavailable() *GetHealthcheckReadyServiceUnavailable {

	return &GetHealthcheckReadyServiceUnavailable{}
}

// WithPayload adds the payload to the get healthcheck ready service unavailable response
func (o *GetHealthcheckReadyServiceUnavailable) WithPayload(payload *models.APIResponse) *GetHealthcheckReadyServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get healthcheck ready service unavailable response
func (o *GetHealthcheckReadyServiceUnavailable) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthcheckReadyServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
