// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CertificateTemplate certificate template
//
// swagger:model CertificateTemplate
type CertificateTemplate struct {

	// issuer id
	IssuerID string `json:"issuer_id,omitempty"`

	// issuer name
	IssuerName string `json:"issuer_name,omitempty"`

	// source type
	SourceType string `json:"source_type,omitempty"`

	// template key
	TemplateKey string `json:"template_key,omitempty"`

	// template source
	TemplateSource string `json:"template_source,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this certificate template
func (m *CertificateTemplate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this certificate template based on context it is used
func (m *CertificateTemplate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CertificateTemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CertificateTemplate) UnmarshalBinary(b []byte) error {
	var res CertificateTemplate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
