// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IssueTransferableTokenPayload issue transferable token payload
//
// swagger:model IssueTransferableTokenPayload
type IssueTransferableTokenPayload struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// unix timestamp in second (UTC)
	ExpiryDate int64 `json:"expiry_date,omitempty"`

	// issuer token id
	IssuerTokenID string `json:"issuer_token_id,omitempty"`

	// monthly token quota
	MonthlyTokenQuota int64 `json:"monthly_token_quota,omitempty"`

	// recipient
	Recipient string `json:"recipient,omitempty"`

	// token id
	TokenID string `json:"token_id,omitempty"`
}

// Validate validates this issue transferable token payload
func (m *IssueTransferableTokenPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this issue transferable token payload based on context it is used
func (m *IssueTransferableTokenPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IssueTransferableTokenPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IssueTransferableTokenPayload) UnmarshalBinary(b []byte) error {
	var res IssueTransferableTokenPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
